markdown: rdiscount
permalink: /:title/
url: shengofsun.github.com
name: ShengOfSun的博客
author: ShengOfSun
email: luckyweijie@gmail.com
duoshuo: shengofbig
weibo: 1677784961
github: shengofsun
pygments: true
safe: true
paginate: 20
truncate: 300
about: "这是我的个人博客"
