markdown: rdiscount
permalink: /:title/
url: http://www.shengofsun.com
name: 我的精神家园
author: ShengOfSun
email: luckyweijie@gmail.com
duoshuo: shengofsun
weibo: 1677784961
github: shengofsun
highlighter: pygments
safe: true
paginate: 20
about: "孔武有力者立功，情操高尚者立德，内心强大者立言。对于注定要在史书上留下一角的人，人生从来都是这么玩的。而对于平凡人，却又是另一套规则。而这套规则呢，孔老夫子早在2000多年前就在他的官方微博(@论语)中为我们制定好了：<br/><br/>
君子食无求饱，居无求安，敏于事而慎于言，就有道而正焉，可谓好学也已。<br/><br/>
作为一个平凡的码农加理工男，我也一直都照着敏于事而慎于言这样的标准行事：静心求学，踏实做事，在数学、编程和其他的理科乐趣中自得其乐。遇到有会意的地方，还能像五柳先生那样欣然忘食。长久以来，一直过着这种悠然自得的生活，也从未未觉得有过任何不妥。<br/><br/>
但在大概一年前左右，这样的状态被室友打破了。那时他一直在寻思着找个地方写博客，于是也便撺掇我去做个个人主页出来，还说这在将来找IT工作时是非常有好处的。就这样，带着极其功利的想法，我开始为自己并不丰厚的技术知识寻找起存储仓库来了。在CSDN和博客园等国内站点几作辗转后，我最终还是投向了github pages的怀抱。选择它的原因，很多码农们也自然都用高大上的语言解释过了：github是程序员专属的社交网络，github pages做的主页定制性高，用git管理具有很强的灵活性——说人话的话，就是难用、逼格高。<br/><br/>
已经厌倦了装逼的我，自是没想到会选这么个地方来写博客的。但好歹逼都装到这份上了，就索性一条道走到黑得了。于是我心一横，就又顺手买了个域名。——有些事情真是不敢想像，作为一个抠门的人，我居然会把闲钱花在这个上面。<br/><br/>
如果仔细推敲起来的话，大概也就是程序员这个行业群体把我推到这条路上来的。他们心思单纯却极具理想化；他们沉稳木讷却极有表现欲望；他们明明只是一颗螺丝钉，却希望全世界都能听到自己的声音。就是这样的一群人，才让圈子里做个人主页蔚然成风。而我呢，其实就是被赶上架的鸭子，只是跟风而已。<br/><br/>
可当有了这个东西之后，却发现相较于技术文章，自己更喜欢写其他的东西。就这样，明明计划要写点儿技术上的点滴，摇身一变成了寄托自己情感世界的安乐窝了。我也不知道，这究竟是生活给我开的玩笑，还是它带给我的惊喜。<br/><br/>
但不管怎么说，这样的结果是我喜欢的。作为一个毫无资本的闷骚青年，扛着单反各地旅行的文艺范儿显然是不适合我的。而写写文章自娱自乐，打发打发自己的闷骚情怀，确是个不错的选择。<br/><br/>
于是我就决定在这里安家了。考虑到我是自己这个站点唯一的读者，我就肆无忌惮的闷骚到底了。名称，不如就套用王小波，叫它个<B>我的精神家园</B>。
"
