markdown: rdiscount
permalink: /:title/
url: http://www.shengofsun.com
name: 我的精神家园
author: ShengOfSun
email: luckyweijie@gmail.com
duoshuo: shengofbig
weibo: 1677784961
github: shengofsun
highlighter: pygments
safe: true
paginate: 20
about: "孔武有力者立功，情操高尚者立德，内心强大者立言。对于注定要在史书上留下一角的人，人生从来都是这么玩的。而对于平凡人，却又是另一套规则。这套规则是孔老夫子在他的官方微博(@论语)中为我们制定的：<br/><br/>
君子食无求饱，居无求安，敏于事而慎于言，就有道而正焉，可谓好学也已。<br/><br/>
于是作为一个平凡的码农加理工男，我也一直都照着敏于事而慎于言这样的标准行事：静心求学，踏实做事，在数学、编程和其他的理科乐趣中自得其乐。遇到有会意的地方，还能像五柳先生那样欣然忘食。长久以来，这种悠然自得的生活并未觉得有什么不妥。<br/><br/>
这样的状态是在大概一年前被室友打破的。那时他一直在寻思着找个地方写博客，于是也便推荐我去做个个人主页出来，还说这在将来找IT的工作时是非常有好处的。就这样，我带着极其功利的角度，开始为自己并不丰厚的技术知识寻找一个可以堆放的落脚点。在CSDN和博客园等国内站点几作辗转后，我最终还是投向了github pages的怀抱。选择它的原因，很多人自然都解释过了：github是程序员专属的社交网络，github pages做的主页定制性高，用git管理具有很强的灵活性——如果用人话来概括一下，就是难用、逼格高。<br/><br/>
装逼都装到这份上了，就索性一条道走到黑。于是我把心一横，就顺手买了个域名。——有些事情真是不敢想像，作为一个抠门的人，我居然会把闲钱花在这个上面。<br/><br/>
如果仔细推敲起来的话，大概也就是程序员这个行业群体把我推到这条路上来的。他们心思单纯却极具理想化；他们沉稳木讷却极有表现欲望；他们明明只是一颗螺丝钉，却希望全世界都能听到自己的声音。就是这样的一群人，才让圈子里做个人主页蔚然成风。而我呢，其实就是被赶上架的鸭子，只是跟风而已。<br/><br/>
可当有了这个东西之后，却发现相较于写技术文章，自己更喜欢写其他的东西。就这样，计划的很好的堆放技术知识的仓库，摇身一变成了寄托自己情感世界的安乐窝。我也不知道，这究竟是生活给我开的玩笑，还是它带给我的惊喜。
"
